IF NOT EXISTS(SELECT principal_id FROM sys.database_principals WHERE name = '__FUNCTION_NAME__') BEGIN
	CREATE USER [__FUNCTION_NAME__] FROM EXTERNAL PROVIDER
END

ALTER ROLE db_datareader ADD MEMBER [__FUNCTION_NAME__];
ALTER ROLE db_datawriter ADD MEMBER [__FUNCTION_NAME__];
ALTER ROLE db_ddladmin ADD MEMBER [__FUNCTION_NAME__];

IF NOT EXISTS(SELECT principal_id FROM sys.database_principals WHERE name = '__FUNCTION_NAME__/slots/__SLOTNAME__') BEGIN
	CREATE USER [__FUNCTION_NAME__/slots/__SLOTNAME__] FROM EXTERNAL PROVIDER
END

ALTER ROLE db_datareader ADD MEMBER [__FUNCTION_NAME__/slots/__SLOTNAME__];
ALTER ROLE db_datawriter ADD MEMBER [__FUNCTION_NAME__/slots/__SLOTNAME__];
ALTER ROLE db_ddladmin ADD MEMBER [__FUNCTION_NAME__/slots/__SLOTNAME__];

