namespace FunderService.Mappers
{
    using AzureFunderCommonMessages.DotNet.Models;
    using AzureFunderCommonMessages.DotNet.Types.ValueConstants;
    using FunderApi;
    using System;
    using System.Drawing;
    using System.Drawing.Printing;
    using System.Runtime.CompilerServices;
    using System.Runtime.Intrinsics.X86;
    using System.Security.Policy;
    using FunderNationality = FunderApi.Nationality;
    using Nationality = AzureFunderCommonMessages.DotNet.Types.ValueConstants.Nationality;

    public static class NationalityMapper
    {
        public static FunderNationality Map(string nationality)
        {
            return nationality.ToLower() switch
            {
                Nationality.Andorran => FunderNationality.Andorra,
                Nationality.Afghan => FunderNationality.Afghanistan,
                Nationality.Albanian => FunderNationality.Albania,
                Nationality.Armenian => FunderNationality.Armenia,
                Nationality.Angolan => FunderNationality.Angola,
                Nationality.Argentine => FunderNationality.Argentina,
                Nationality.American => FunderNationality.American_Samoa,
                Nationality.Austrian => FunderNationality.Austria,
                Nationality.Australian => FunderNationality.Australia,
                Nationality.Aruban => FunderNationality.Aruba,
                Nationality.Azeri => FunderNationality.Azerbaijan,
                Nationality.Bosnian => FunderNationality.Bosnia_Herzegovina,
                Nationality.Barbadian => FunderNationality.Barbados,
                Nationality.Bangladeshi => FunderNationality.Bangladesh,
                Nationality.Belgian => FunderNationality.Belgium,
                Nationality.Burkinabe => FunderNationality.Burkina_Faso,
                Nationality.Bulgarian => FunderNationality.Bulgaria,
                Nationality.Bahraini => FunderNationality.Bahrain,
                Nationality.Burundian => FunderNationality.Burundi,
                Nationality.Bermudian => FunderNationality.Bermuda,
                Nationality.Brazilian => FunderNationality.Brazil,
                Nationality.Bahamian => FunderNationality.Bahamas,
                Nationality.Belarusian => FunderNationality.Belarus,
                Nationality.Belizean => FunderNationality.Belize,
                Nationality.Canadian => FunderNationality.Canada,
                Nationality.Congolese => FunderNationality.Congo,
                Nationality.Chilean => FunderNationality.Chile,
                Nationality.Cameroonian => FunderNationality.Cameroon,
                Nationality.Chinese => FunderNationality.China,
                Nationality.Colombian => FunderNationality.Colombia,
                Nationality.Cuban => FunderNationality.Cuba,
                Nationality.CapeVerdean => FunderNationality.Cape_Verde,
                Nationality.Cypriot => FunderNationality.Cyprus,
                Nationality.Czech => FunderNationality.Czech_Republic,
                Nationality.German => FunderNationality.Germany,
                Nationality.DominicansRepublic => FunderNationality.Dominican_Republic,
                Nationality.Algerian => FunderNationality.Algeria,
                Nationality.Ecuadorian => FunderNationality.Ecuador,
                Nationality.Estonian => FunderNationality.Estonia,
                Nationality.Egyptian => FunderNationality.Egypt,
                Nationality.Eritrean => FunderNationality.Eritrea,
                Nationality.Spaniard => FunderNationality.Spain,
                Nationality.Ethiopian => FunderNationality.Ethiopia,
                Nationality.Fijian => FunderNationality.Fiji,
                Nationality.Faroese => FunderNationality.Faroe_Islands,
                Nationality.Grenadian => FunderNationality.Grenada,
                Nationality.Georgian => FunderNationality.Georgia,
                Nationality.GuianeseFrench => FunderNationality.French_Guiana,
                Nationality.Ghanaian => FunderNationality.Ghana,
                Nationality.Gibraltar => FunderNationality.Gibraltar,
                Nationality.Guinean => FunderNationality.Guinea,
                Nationality.Guatemalan => FunderNationality.Guatemala,
                Nationality.GuineaBissauNational => FunderNationality.GuineaBissau,
                Nationality.Guyanese => FunderNationality.Guyana,
                Nationality.Honduran => FunderNationality.Honduras,
                Nationality.Croatian => FunderNationality.Croatia,
                Nationality.Haitian => FunderNationality.Haiti,
                Nationality.Hungarian => FunderNationality.Hungary,
                Nationality.Indonesian => FunderNationality.Indonesia,
                Nationality.Israeli => FunderNationality.Israel,
                Nationality.Indian => FunderNationality.India,
                Nationality.Iraqi => FunderNationality.Iraq,
                Nationality.IraniansPersians => FunderNationality.Iran,
                Nationality.Icelander => FunderNationality.Iceland,
                Nationality.Italian => FunderNationality.Italy,
                Nationality.Jamaican => FunderNationality.Jamaica,
                Nationality.Jordanian => FunderNationality.Jordan,
                Nationality.Japanese => FunderNationality.Japan,
                Nationality.Kenyan => FunderNationality.Kenya,
                Nationality.Cambodian => FunderNationality.Cambodia,
                Nationality.Comorian => FunderNationality.Comoros,
                Nationality.KoreanNorth => FunderNationality.North_Korea,
                Nationality.KoreanSouth => FunderNationality.South_Korea,
                Nationality.Kuwaiti => FunderNationality.Kuwait,
                Nationality.Lao => FunderNationality.Laos,
                Nationality.Lebanese => FunderNationality.Lebanon,
                Nationality.Liechtensteiner => FunderNationality.Liechtenstein,
                Nationality.SriLankan => FunderNationality.Sri_Lanka,
                Nationality.Liberian => FunderNationality.Liberia,
                Nationality.Lithuanian => FunderNationality.Lithuania,
                Nationality.Luxembourger => FunderNationality.Luxembourg,
                Nationality.Latvian => FunderNationality.Latvia,
                Nationality.Libyan => FunderNationality.Libya,
                Nationality.Moroccan => FunderNationality.Morocco,
                Nationality.Moldovan => FunderNationality.Moldova,
                Nationality.Montenegrin => FunderNationality.Montenegro,
                Nationality.Macedonian => FunderNationality.Macedonia,
                Nationality.Malian => FunderNationality.Mali,
                Nationality.Mongolian => FunderNationality.Mongolia,
                Nationality.Maltese => FunderNationality.Malta,
                Nationality.Mauritian => FunderNationality.Mauritius,
                Nationality.Maldivian => FunderNationality.Maldives,
                Nationality.Malawian => FunderNationality.Malawi,
                Nationality.Mexican => FunderNationality.Mexico,
                Nationality.Namibian => FunderNationality.Namibia,
                Nationality.Nigerien => FunderNationality.Niger,
                Nationality.Nigerian => FunderNationality.Nigeria,
                Nationality.Nepalese => FunderNationality.Nepal,
                Nationality.NewZealander => FunderNationality.New_Zealand,
                Nationality.Panamanian => FunderNationality.Panama,
                Nationality.Peruvian => FunderNationality.Peru,
                Nationality.PapuaNewGuinean => FunderNationality.Papua_New_Guinea,
                Nationality.Pakistani => FunderNationality.Pakistan,
                Nationality.PuertoRican => FunderNationality.Puerto_Rico,
                Nationality.Palestinian => FunderNationality.Palestine,
                Nationality.Portuguese => FunderNationality.Portugal,
                Nationality.Palauan => FunderNationality.Palau,
                Nationality.Paraguayan => FunderNationality.Paraguay,
                Nationality.Reunionnai => FunderNationality.Reunion,
                Nationality.Romanian => FunderNationality.Romania,
                Nationality.Russian => FunderNationality.Russia,
                Nationality.Rwandan => FunderNationality.Rwanda,
                Nationality.Saudi => FunderNationality.Saudi_Arabia,
                Nationality.Sudanese => FunderNationality.Sudan,
                Nationality.Swede => FunderNationality.Sweden,
                Nationality.Singaporean => FunderNationality.Singapore,
                Nationality.SierraLeonean => FunderNationality.Sierra_Leone,
                Nationality.Senegalese => FunderNationality.Senegal,
                Nationality.Somali => FunderNationality.Somalia,
                Nationality.Surinamese => FunderNationality.Suriname,
                Nationality.SaoTomeAndPrincipe => FunderNationality.Sao_Tome___Principe,
                Nationality.Salvadoran => FunderNationality.El_Salvador,
                Nationality.Syrian => FunderNationality.Syria,
                Nationality.Chadian => FunderNationality.Chad,
                Nationality.Thai => FunderNationality.Thailand,
                Nationality.Trinidadian => FunderNationality.Trinidad___Tobago,
                Nationality.Tuvaluan => FunderNationality.Tuvalu,
                Nationality.Taiwanese => FunderNationality.Taiwan,
                Nationality.Tanzanian => FunderNationality.Tanzania,
                Nationality.Ukrainian => FunderNationality.Ukraine,
                Nationality.Ugandan => FunderNationality.Uganda,
                Nationality.Uruguayan => FunderNationality.Uruguay,
                Nationality.Uzbek => FunderNationality.Uzbekistan,
                Nationality.Venezuelan => FunderNationality.Venezuela,
                Nationality.BritishVirginIslander => FunderNationality.Virgin_Islands__British_,
                Nationality.Vietnamese => FunderNationality.Vietnam,
                Nationality.Vanuatuan => FunderNationality.Vanuatu,
                Nationality.Yemeni => FunderNationality.Yemen,
                Nationality.SouthAfrican => FunderNationality.South_Africa,
                Nationality.Zambian => FunderNationality.Zambia,
                Nationality.Zimbabwean => FunderNationality.Zimbabwe,
                Nationality.British => FunderNationality.United_Kingdom,
                _ => FunderNationality.United_Kingdom
            };
        }
    }
}