// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using AzureFunderCommonMessages.DotNet.Request;
//
//    var welcome = Welcome.FromJson(jsonString);
using AzureFunderCommonMessages.DotNet.Request.DataTypes;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;

namespace AzureFunderCommonMessages.DotNet.Request
{
    public class AdditionalData : BaseCommonRequest
    {
        public AdditionalData()
        {
            Data = new();
        }
        [JsonProperty("data", Required = Required.Always)]
        public new AdditionalDataObject Data { get; set; }

    }
}
