// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using AzureFunderCommonMessages.DotNet.Request;
//
//    var welcome = Welcome.FromJson(jsonString);
using AzureFunderCommonMessages.DotNet.Request.DataTypes;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;

namespace AzureFunderCommonMessages.DotNet.Request
{
    public class ApplicationRequest : BaseCommonRequest
    {
        public ApplicationRequest()
        {
            Data = new ApplicationRequestData();
        }

        [JsonProperty("data", Required = Required.Always)]
        public new ApplicationRequestData Data { get; set; }

    }
}
