// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using AzureFunderCommonMessages.DotNet.Request;
//
//    var welcome = Welcome.FromJson(jsonString);
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;

namespace AzureFunderCommonMessages.DotNet.Request
{
    public class GetEsign : BaseCommonRequest
    {

    }
}
