namespace UnitTests.DomainLayerTests.FunderService.Mappers;


using global::FunderService.Mappers;
using global::FunderService.Mappers.Interfaces;
using Microsoft.Extensions.Logging;
using Moq;
using Orchestrator.Exceptions;
using Orchestrator.Triggers;
using FunderNationality = FunderApi.Nationality;
using Nationality = AzureFunderCommonMessages.DotNet.Types.ValueConstants;
public class NationalityMapperTests
{    
    [Test]
    public void NationalityMapperSuccessTests()
    {
        string nationalityTypeExpected0 = "Andorra";
        string nationalityTypeActual0 = NationalityMapper.Map("Andorran").ToString();
        string nationalityTypeExpected1 = "Afghanistan";
        string nationalityTypeActual1 = NationalityMapper.Map("Afghan").ToString();
        string nationalityTypeExpected2 = "Albania";
        string nationalityTypeActual2 = NationalityMapper.Map("Albanian").ToString();
        string nationalityTypeExpected3 = "Armenia";
        string nationalityTypeActual3 = NationalityMapper.Map("Armenian").ToString();
        string nationalityTypeExpected4 = "Angola";
        string nationalityTypeActual4 = NationalityMapper.Map("Angolan").ToString();
        string nationalityTypeExpected5 = "Argentina";
        string nationalityTypeActual5 = NationalityMapper.Map("Argentine").ToString();
        string nationalityTypeExpected6 = "American_Samoa";
        string nationalityTypeActual6 = NationalityMapper.Map("American").ToString();
        string nationalityTypeExpected7 = "Austria";
        string nationalityTypeActual7 = NationalityMapper.Map("Austrian").ToString();
        string nationalityTypeExpected8 = "Australia";
        string nationalityTypeActual8 = NationalityMapper.Map("Australian").ToString();
        string nationalityTypeExpected9 = "Aruba";
        string nationalityTypeActual9 = NationalityMapper.Map("Aruban").ToString();
        string nationalityTypeExpected10 = "Azerbaijan";
        string nationalityTypeActual10 = NationalityMapper.Map("Azeri").ToString();
        string nationalityTypeExpected11 = "Bosnia_Herzegovina";
        string nationalityTypeActual11 = NationalityMapper.Map("Bosnian").ToString();
        string nationalityTypeExpected12= "Barbados";
        string nationalityTypeActual12 = NationalityMapper.Map("Barbadian").ToString();
        string nationalityTypeExpected13 = "Bangladesh";
        string nationalityTypeActual13 = NationalityMapper.Map("Bangladeshi").ToString();
        string nationalityTypeExpected14 = "Belgium";
        string nationalityTypeActual14 = NationalityMapper.Map("Belgian").ToString();
        string nationalityTypeExpected15 = "Burkina_Faso";
        string nationalityTypeActual15 = NationalityMapper.Map("Burkinabe").ToString();
        string nationalityTypeExpected16 = "Bulgaria";
        string nationalityTypeActual16 = NationalityMapper.Map("Bulgarian").ToString();
        string nationalityTypeExpected17 = "Bahrain";
        string nationalityTypeActual17 = NationalityMapper.Map("Bahraini").ToString();
        string nationalityTypeExpected18 = "Burundi";
        string nationalityTypeActual18 = NationalityMapper.Map("Burundian").ToString();
        string nationalityTypeExpected19 = "Bermuda";
        string nationalityTypeActual19 = NationalityMapper.Map("Bermudian").ToString();
        string nationalityTypeExpected20 = "Brazil";
        string nationalityTypeActual20 = NationalityMapper.Map("Brazilian").ToString();
        string nationalityTypeExpected21 = "Bahamas";
        string nationalityTypeActual21 = NationalityMapper.Map("Bahamian").ToString();
        string nationalityTypeExpected22 = "Belarus";
        string nationalityTypeActual22 = NationalityMapper.Map("Belarusian").ToString();
        string nationalityTypeExpected23 = "Belize";
        string nationalityTypeActual23 = NationalityMapper.Map("Belizean").ToString();
        string nationalityTypeExpected24 = "Congo";
        string nationalityTypeActual24 = NationalityMapper.Map("Congolese").ToString();
        string nationalityTypeExpected25 = "Cameroon";
        string nationalityTypeActual25 = NationalityMapper.Map("Cameroonian").ToString();
        string nationalityTypeExpected26 = "China";
        string nationalityTypeActual26 = NationalityMapper.Map("Chinese").ToString();
        string nationalityTypeExpected27 = "Colombia";
        string nationalityTypeActual27 = NationalityMapper.Map("Colombian").ToString();
        string nationalityTypeExpected28 = "Cuba";
        string nationalityTypeActual28 = NationalityMapper.Map("Cuban").ToString();
        string nationalityTypeExpected29 = "Cape_Verde";
        string nationalityTypeActual29 = NationalityMapper.Map("cape verdean").ToString();
        string nationalityTypeExpected30 = "Cyprus";
        string nationalityTypeActual30 = NationalityMapper.Map("cypriot").ToString();
        string nationalityTypeExpected31 = "Czech_Republic";
        string nationalityTypeActual31 = NationalityMapper.Map("czech").ToString();
        string nationalityTypeExpected32 = "Germany";
        string nationalityTypeActual32 = NationalityMapper.Map("german").ToString();
        string nationalityTypeExpected33 = "Dominican_Republic";
        string nationalityTypeActual33 = NationalityMapper.Map("dominicans (republic)").ToString();
        string nationalityTypeExpected34 = "Algeria";
        string nationalityTypeActual34 = NationalityMapper.Map("algerian").ToString();
        string nationalityTypeExpected35 = "Ecuador";
        string nationalityTypeActual35 = NationalityMapper.Map("ecuadorian").ToString();
        string nationalityTypeExpected36 = "Estonia";
        string nationalityTypeActual36 = NationalityMapper.Map("estonian").ToString();
        string nationalityTypeExpected37 = "Egypt";
        string nationalityTypeActual37 = NationalityMapper.Map("egyptian").ToString();
        string nationalityTypeExpected38 = "Eritrea";
        string nationalityTypeActual38 = NationalityMapper.Map("eritrean").ToString();
        string nationalityTypeExpected39 = "Spain";
        string nationalityTypeActual39 = NationalityMapper.Map("spaniard").ToString();
        string nationalityTypeExpected40 = "Ethiopia";
        string nationalityTypeActual40 = NationalityMapper.Map("ethiopian").ToString();
        string nationalityTypeExpected41 = "Fiji";
        string nationalityTypeActual41 = NationalityMapper.Map("fijian").ToString();
        string nationalityTypeExpected42 = "Faroe_Islands";
        string nationalityTypeActual42 = NationalityMapper.Map("faroese").ToString();
        string nationalityTypeExpected43 = "Grenada";
        string nationalityTypeActual43 = NationalityMapper.Map("grenadian").ToString();
        string nationalityTypeExpected44 = "Georgia";
        string nationalityTypeActual44 = NationalityMapper.Map("georgian").ToString();
        string nationalityTypeExpected45 = "French_Guiana";
        string nationalityTypeActual45 = NationalityMapper.Map("guianese (french)").ToString();
        string nationalityTypeExpected46 = "Ghana";
        string nationalityTypeActual46 = NationalityMapper.Map("ghanaian").ToString();
        string nationalityTypeExpected47 = "Gibraltar";
        string nationalityTypeActual47 = NationalityMapper.Map("gibraltar").ToString();
        string nationalityTypeExpected48 = "Guinea";
        string nationalityTypeActual48 = NationalityMapper.Map("guinean").ToString();
        string nationalityTypeExpected49 = "Guatemala";
        string nationalityTypeActual49 = NationalityMapper.Map("guatemalan").ToString();
        string nationalityTypeExpected50 = "GuineaBissau";
        string nationalityTypeActual50 = NationalityMapper.Map("guinea-bissau national").ToString();
        string nationalityTypeExpected51 = "Guyana";
        string nationalityTypeActual51 = NationalityMapper.Map("guyanese").ToString();
        string nationalityTypeExpected52 = "Honduras";
        string nationalityTypeActual52 = NationalityMapper.Map("honduran").ToString();
        string nationalityTypeExpected53 = "Croatia";
        string nationalityTypeActual53 = NationalityMapper.Map("croatian").ToString();
        string nationalityTypeExpected54 = "Haiti";
        string nationalityTypeActual54 = NationalityMapper.Map("haitian").ToString();
        string nationalityTypeExpected55 = "Hungary";
        string nationalityTypeActual55 = NationalityMapper.Map("hungarian").ToString();
        string nationalityTypeExpected56 = "Indonesia";
        string nationalityTypeActual56 = NationalityMapper.Map("indonesian").ToString();
        string nationalityTypeExpected57 = "Israel";
        string nationalityTypeActual57 = NationalityMapper.Map("israeli").ToString();
        string nationalityTypeExpected58 = "India";
        string nationalityTypeActual58 = NationalityMapper.Map("indian").ToString();
        string nationalityTypeExpected59 = "Iraq";
        string nationalityTypeActual59 = NationalityMapper.Map("iraqi").ToString();
        string nationalityTypeExpected60 = "Iran";
        string nationalityTypeActual60 = NationalityMapper.Map("iranians (persians)").ToString();
        string nationalityTypeExpected61 = "Iceland";
        string nationalityTypeActual61 = NationalityMapper.Map("icelander").ToString();
        string nationalityTypeExpected62 = "Italy";
        string nationalityTypeActual62 = NationalityMapper.Map("italian").ToString();
        string nationalityTypeExpected63 = "Jamaica";
        string nationalityTypeActual63 = NationalityMapper.Map("jamaican").ToString();
        string nationalityTypeExpected64 = "Jordan";
        string nationalityTypeActual64 = NationalityMapper.Map("jordanian").ToString();
        string nationalityTypeExpected65 = "Japan";
        string nationalityTypeActual65 = NationalityMapper.Map("japanese").ToString();
        string nationalityTypeExpected66 = "Kenya";
        string nationalityTypeActual66 = NationalityMapper.Map("kenyan").ToString();
        string nationalityTypeExpected67 = "Cambodia";
        string nationalityTypeActual67 = NationalityMapper.Map("cambodian").ToString();
        string nationalityTypeExpected68 = "Comoros";
        string nationalityTypeActual68 = NationalityMapper.Map("comorian").ToString();
        string nationalityTypeExpected69 = "North_Korea";
        string nationalityTypeActual69 = NationalityMapper.Map("korean (north)").ToString();
        string nationalityTypeExpected70 = "South_Korea";
        string nationalityTypeActual70 = NationalityMapper.Map("korean (south)").ToString();
        string nationalityTypeExpected71 = "Kuwait";
        string nationalityTypeActual71 = NationalityMapper.Map("kuwaiti").ToString();
        string nationalityTypeExpected72 = "Laos";
        string nationalityTypeActual72 = NationalityMapper.Map("lao").ToString();
        string nationalityTypeExpected73 = "Lebanon";
        string nationalityTypeActual73 = NationalityMapper.Map("lebanese").ToString();
        string nationalityTypeExpected74 = "Liechtenstein";
        string nationalityTypeActual74 = NationalityMapper.Map("liechtensteiner").ToString();
        string nationalityTypeExpected75 = "Sri_Lanka";
        string nationalityTypeActual75 = NationalityMapper.Map("sri lankan").ToString();
        string nationalityTypeExpected76 = "Liberia";
        string nationalityTypeActual76 = NationalityMapper.Map("liberian").ToString();
        string nationalityTypeExpected77 = "Lithuania";
        string nationalityTypeActual77 = NationalityMapper.Map("lithuanian").ToString();
        string nationalityTypeExpected78 = "Luxembourg";
        string nationalityTypeActual78 = NationalityMapper.Map("luxembourger").ToString();
        string nationalityTypeExpected79 = "Latvia";
        string nationalityTypeActual79 = NationalityMapper.Map("latvian").ToString();
        string nationalityTypeExpected80 = "Libya";
        string nationalityTypeActual80 = NationalityMapper.Map("libyan").ToString();
        string nationalityTypeExpected81 = "Morocco";
        string nationalityTypeActual81 = NationalityMapper.Map("moroccan").ToString();
        string nationalityTypeExpected82 = "Moldova";
        string nationalityTypeActual82 = NationalityMapper.Map("moldovan").ToString();
        string nationalityTypeExpected83 = "Montenegro";
        string nationalityTypeActual83 = NationalityMapper.Map("montenegrin").ToString();
        string nationalityTypeExpected84 = "Macedonia";
        string nationalityTypeActual84 = NationalityMapper.Map("macedonian").ToString();
        string nationalityTypeExpected85 = "Mali";
        string nationalityTypeActual85 = NationalityMapper.Map("malian").ToString();
        string nationalityTypeExpected86 = "Mongolia";
        string nationalityTypeActual86 = NationalityMapper.Map("mongolian").ToString();
        string nationalityTypeExpected87 = "Malta";
        string nationalityTypeActual87 = NationalityMapper.Map("maltese").ToString();
        string nationalityTypeExpected88 = "Mauritius";
        string nationalityTypeActual88 = NationalityMapper.Map("mauritian").ToString();
        string nationalityTypeExpected89 = "Maldives";
        string nationalityTypeActual89 = NationalityMapper.Map("maldivian").ToString();
        string nationalityTypeExpected90 = "Malawi";
        string nationalityTypeActual90 = NationalityMapper.Map("malawian").ToString();
        string nationalityTypeExpected91 = "Mexico";
        string nationalityTypeActual91 = NationalityMapper.Map("mexican").ToString();
        string nationalityTypeExpected92 = "Namibia";
        string nationalityTypeActual92 = NationalityMapper.Map("namibian").ToString();
        string nationalityTypeExpected93 = "Niger";
        string nationalityTypeActual93 = NationalityMapper.Map("nigerien").ToString();
        string nationalityTypeExpected94 = "Nigeria";
        string nationalityTypeActual94 = NationalityMapper.Map("nigerian").ToString();
        string nationalityTypeExpected95 = "Nepal";
        string nationalityTypeActual95 = NationalityMapper.Map("nepalese").ToString();
        string nationalityTypeExpected96 = "New_Zealand";
        string nationalityTypeActual96 = NationalityMapper.Map("new zealander").ToString();
        string nationalityTypeExpected97 = "Panama";
        string nationalityTypeActual97 = NationalityMapper.Map("panamanian").ToString();
        string nationalityTypeExpected98 = "Peru";
        string nationalityTypeActual98 = NationalityMapper.Map("peruvian").ToString();
        string nationalityTypeExpected99 = "Papua_New_Guinea";
        string nationalityTypeActual99 = NationalityMapper.Map("papua new guinean").ToString();
        string nationalityTypeExpected100 = "Pakistan";
        string nationalityTypeActual100 = NationalityMapper.Map("pakistani").ToString();
        string nationalityTypeExpected101 = "Puerto_Rico";
        string nationalityTypeActual101 = NationalityMapper.Map("puerto rican").ToString();
        string nationalityTypeExpected102 = "Palestine";
        string nationalityTypeActual102 = NationalityMapper.Map("palestinian").ToString();
        string nationalityTypeExpected103 = "Portugal";
        string nationalityTypeActual103 = NationalityMapper.Map("portuguese").ToString();
        string nationalityTypeExpected104 = "Palau";
        string nationalityTypeActual104 = NationalityMapper.Map("palauan").ToString();
        string nationalityTypeExpected105 = "Paraguay";
        string nationalityTypeActual105 = NationalityMapper.Map("paraguayan").ToString();
        string nationalityTypeExpected106 = "Reunion";
        string nationalityTypeActual106 = NationalityMapper.Map("reunionnai").ToString();
        string nationalityTypeExpected107 = "Romania";
        string nationalityTypeActual107 = NationalityMapper.Map("romanian").ToString();
        string nationalityTypeExpected108 = "Russia";
        string nationalityTypeActual108 = NationalityMapper.Map("russian").ToString();
        string nationalityTypeExpected109 = "Rwanda";
        string nationalityTypeActual109 = NationalityMapper.Map("rwandan").ToString();
        string nationalityTypeExpected110 = "Saudi_Arabia";
        string nationalityTypeActual110 = NationalityMapper.Map("saudi").ToString();
        string nationalityTypeExpected111 = "Sudan";
        string nationalityTypeActual111 = NationalityMapper.Map("sudanese").ToString();
        string nationalityTypeExpected112 = "Sweden";
        string nationalityTypeActual112 = NationalityMapper.Map("swede").ToString();
        string nationalityTypeExpected113 = "Singapore";
        string nationalityTypeActual113 = NationalityMapper.Map("singaporean").ToString();
        string nationalityTypeExpected114 = "Sierra_Leone";
        string nationalityTypeActual114 = NationalityMapper.Map("sierra leonean").ToString();
        string nationalityTypeExpected115 = "Senegal";
        string nationalityTypeActual115 = NationalityMapper.Map("senegalese").ToString();
        string nationalityTypeExpected116 = "Somalia";
        string nationalityTypeActual116 = NationalityMapper.Map("somali").ToString();
        string nationalityTypeExpected117 = "Suriname";
        string nationalityTypeActual117 = NationalityMapper.Map("surinamese").ToString();
        string nationalityTypeExpected118 = "Sao_Tome___Principe";
        string nationalityTypeActual118 = NationalityMapper.Map("sao tome and principe").ToString();
        string nationalityTypeExpected119 = "El_Salvador";
        string nationalityTypeActual119 = NationalityMapper.Map("salvadoran").ToString();
        string nationalityTypeExpected120 = "Syria";
        string nationalityTypeActual120 = NationalityMapper.Map("syrian").ToString();
        string nationalityTypeExpected121 = "Chad";
        string nationalityTypeActual121 = NationalityMapper.Map("chadian").ToString();
        string nationalityTypeExpected122 = "Thailand";
        string nationalityTypeActual122 = NationalityMapper.Map("thai").ToString();
        string nationalityTypeExpected123 = "Trinidad___Tobago";
        string nationalityTypeActual123 = NationalityMapper.Map("trinidadian").ToString();
        string nationalityTypeExpected124 = "Tuvalu";
        string nationalityTypeActual124 = NationalityMapper.Map("Tuvaluan").ToString();
        string nationalityTypeExpected125 = "Taiwan";
        string nationalityTypeActual125 = NationalityMapper.Map("Taiwanese").ToString();
        string nationalityTypeExpected126 = "Ukraine";
        string nationalityTypeActual126 = NationalityMapper.Map("Ukrainian").ToString();
        string nationalityTypeExpected127 = "Uganda";
        string nationalityTypeActual127 = NationalityMapper.Map("ugandan").ToString();
        string nationalityTypeExpected128 = "Uruguay";
        string nationalityTypeActual128 = NationalityMapper.Map("uruguayan").ToString();
        string nationalityTypeExpected129 = "Uzbekistan";
        string nationalityTypeActual129 = NationalityMapper.Map("uzbek").ToString();
        string nationalityTypeExpected130 = "Venezuela";
        string nationalityTypeActual130 = NationalityMapper.Map("venezuelan").ToString();
        string nationalityTypeExpected131 = "Virgin_Islands__British_";
        string nationalityTypeActual131 = NationalityMapper.Map("british virgin islander").ToString();
        string nationalityTypeExpected132 = "Vietnam";
        string nationalityTypeActual132 = NationalityMapper.Map("vietnamese").ToString();
        string nationalityTypeExpected133 = "Vanuatu";
        string nationalityTypeActual133 = NationalityMapper.Map("vanuatuan").ToString();
        string nationalityTypeExpected134 = "Yemen";
        string nationalityTypeActual134 = NationalityMapper.Map("yemeni").ToString();
        string nationalityTypeExpected135 = "South_Africa";
        string nationalityTypeActual135 = NationalityMapper.Map("south african").ToString();
        string nationalityTypeExpected136 = "Zambia";
        string nationalityTypeActual136 = NationalityMapper.Map("zambian").ToString();
        string nationalityTypeExpected137 = "Zimbabwe";
        string nationalityTypeActual137 = NationalityMapper.Map("zimbabwean").ToString();
        string nationalityTypeExpected138 = "Tanzania";
        string nationalityTypeActual138 = NationalityMapper.Map("tanzanian").ToString();
        string nationalityTypeExpected139 = "United_Kingdom";
        string nationalityTypeActual139 = NationalityMapper.Map("british").ToString();
        string nationalityTypeExpected140 = "Canada";
        string nationalityTypeActual140 = NationalityMapper.Map("canadian").ToString(); 
        string nationalityTypeExpected141 = "Chile";
        string nationalityTypeActual141 = NationalityMapper.Map("chilean").ToString();
        string nationalityTypeExpected142 = "United_Kingdom";
        string nationalityTypeActual142 = NationalityMapper.Map("").ToString();

        Assert.Multiple(() =>
        {
            Assert.That(nationalityTypeExpected1, Is.EqualTo(nationalityTypeActual1));
            Assert.That(nationalityTypeExpected2, Is.EqualTo(nationalityTypeActual2));
            Assert.That(nationalityTypeExpected3, Is.EqualTo(nationalityTypeActual3));
            Assert.That(nationalityTypeExpected0, Is.EqualTo(nationalityTypeActual0));
            Assert.That(nationalityTypeExpected4, Is.EqualTo(nationalityTypeActual4));
            Assert.That(nationalityTypeExpected5, Is.EqualTo(nationalityTypeActual5));
            Assert.That(nationalityTypeExpected6, Is.EqualTo(nationalityTypeActual6));
            Assert.That(nationalityTypeExpected7, Is.EqualTo(nationalityTypeActual7));
            Assert.That(nationalityTypeExpected8, Is.EqualTo(nationalityTypeActual8));
            Assert.That(nationalityTypeExpected9, Is.EqualTo(nationalityTypeActual9));
            Assert.That(nationalityTypeExpected10, Is.EqualTo(nationalityTypeActual10));
            Assert.That(nationalityTypeExpected11, Is.EqualTo(nationalityTypeActual11));
            Assert.That(nationalityTypeExpected12, Is.EqualTo(nationalityTypeActual12));
            Assert.That(nationalityTypeExpected13, Is.EqualTo(nationalityTypeActual13));
            Assert.That(nationalityTypeExpected14, Is.EqualTo(nationalityTypeActual14));
            Assert.That(nationalityTypeExpected15, Is.EqualTo(nationalityTypeActual15));
            Assert.That(nationalityTypeExpected16, Is.EqualTo(nationalityTypeActual16));
            Assert.That(nationalityTypeExpected17, Is.EqualTo(nationalityTypeActual17));
            Assert.That(nationalityTypeExpected18, Is.EqualTo(nationalityTypeActual18));
            Assert.That(nationalityTypeExpected19, Is.EqualTo(nationalityTypeActual19));
            Assert.That(nationalityTypeExpected20, Is.EqualTo(nationalityTypeActual20));
            Assert.That(nationalityTypeExpected21, Is.EqualTo(nationalityTypeActual21));
            Assert.That(nationalityTypeExpected22, Is.EqualTo(nationalityTypeActual22));
            Assert.That(nationalityTypeExpected23, Is.EqualTo(nationalityTypeActual23));
            Assert.That(nationalityTypeExpected24, Is.EqualTo(nationalityTypeActual24));
            Assert.That(nationalityTypeExpected25, Is.EqualTo(nationalityTypeActual25));
            Assert.That(nationalityTypeExpected26, Is.EqualTo(nationalityTypeActual26));
            Assert.That(nationalityTypeExpected27, Is.EqualTo(nationalityTypeActual27));
            Assert.That(nationalityTypeExpected28, Is.EqualTo(nationalityTypeActual28));
            Assert.That(nationalityTypeExpected29, Is.EqualTo(nationalityTypeActual29));
            Assert.That(nationalityTypeExpected30, Is.EqualTo(nationalityTypeActual30));
            Assert.That(nationalityTypeExpected31, Is.EqualTo(nationalityTypeActual31));                     
            Assert.That(nationalityTypeExpected32, Is.EqualTo(nationalityTypeActual32));
            Assert.That(nationalityTypeExpected33, Is.EqualTo(nationalityTypeActual33));
            Assert.That(nationalityTypeExpected34, Is.EqualTo(nationalityTypeActual34));
            Assert.That(nationalityTypeExpected35, Is.EqualTo(nationalityTypeActual35));
            Assert.That(nationalityTypeExpected36, Is.EqualTo(nationalityTypeActual36));
            Assert.That(nationalityTypeExpected37, Is.EqualTo(nationalityTypeActual37));
            Assert.That(nationalityTypeExpected38, Is.EqualTo(nationalityTypeActual38));
            Assert.That(nationalityTypeExpected39, Is.EqualTo(nationalityTypeActual39));
            Assert.That(nationalityTypeExpected40, Is.EqualTo(nationalityTypeActual40));
            Assert.That(nationalityTypeExpected41, Is.EqualTo(nationalityTypeActual41));
            Assert.That(nationalityTypeExpected42, Is.EqualTo(nationalityTypeActual42));
            Assert.That(nationalityTypeExpected43, Is.EqualTo(nationalityTypeActual43));
            Assert.That(nationalityTypeExpected44, Is.EqualTo(nationalityTypeActual44));
            Assert.That(nationalityTypeExpected45, Is.EqualTo(nationalityTypeActual45));
            Assert.That(nationalityTypeExpected46, Is.EqualTo(nationalityTypeActual46));
            Assert.That(nationalityTypeExpected47, Is.EqualTo(nationalityTypeActual47));
            Assert.That(nationalityTypeExpected48, Is.EqualTo(nationalityTypeActual48));
            Assert.That(nationalityTypeExpected49, Is.EqualTo(nationalityTypeActual49));
            Assert.That(nationalityTypeExpected50, Is.EqualTo(nationalityTypeActual50));
            Assert.That(nationalityTypeExpected51, Is.EqualTo(nationalityTypeActual51));
            Assert.That(nationalityTypeExpected52, Is.EqualTo(nationalityTypeActual52));
            Assert.That(nationalityTypeExpected53, Is.EqualTo(nationalityTypeActual53));
            Assert.That(nationalityTypeExpected54, Is.EqualTo(nationalityTypeActual54));
            Assert.That(nationalityTypeExpected55, Is.EqualTo(nationalityTypeActual55));
            Assert.That(nationalityTypeExpected56, Is.EqualTo(nationalityTypeActual56));
            Assert.That(nationalityTypeExpected57, Is.EqualTo(nationalityTypeActual57));
            Assert.That(nationalityTypeExpected58, Is.EqualTo(nationalityTypeActual58));
            Assert.That(nationalityTypeExpected59, Is.EqualTo(nationalityTypeActual59));
            Assert.That(nationalityTypeExpected60, Is.EqualTo(nationalityTypeActual60));
            Assert.That(nationalityTypeExpected61, Is.EqualTo(nationalityTypeActual61));
            Assert.That(nationalityTypeExpected62, Is.EqualTo(nationalityTypeActual62));
            Assert.That(nationalityTypeExpected63, Is.EqualTo(nationalityTypeActual63));
            Assert.That(nationalityTypeExpected64, Is.EqualTo(nationalityTypeActual64));
            Assert.That(nationalityTypeExpected65, Is.EqualTo(nationalityTypeActual65));
            Assert.That(nationalityTypeExpected66, Is.EqualTo(nationalityTypeActual66));
            Assert.That(nationalityTypeExpected67, Is.EqualTo(nationalityTypeActual67));
            Assert.That(nationalityTypeExpected68, Is.EqualTo(nationalityTypeActual68));
            Assert.That(nationalityTypeExpected69, Is.EqualTo(nationalityTypeActual69));
            Assert.That(nationalityTypeExpected70, Is.EqualTo(nationalityTypeActual70));
            Assert.That(nationalityTypeExpected71, Is.EqualTo(nationalityTypeActual71));
            Assert.That(nationalityTypeExpected72, Is.EqualTo(nationalityTypeActual72));
            Assert.That(nationalityTypeExpected73, Is.EqualTo(nationalityTypeActual73));
            Assert.That(nationalityTypeExpected74, Is.EqualTo(nationalityTypeActual74));
            Assert.That(nationalityTypeExpected75, Is.EqualTo(nationalityTypeActual75));
            Assert.That(nationalityTypeExpected76, Is.EqualTo(nationalityTypeActual76));
            Assert.That(nationalityTypeExpected77, Is.EqualTo(nationalityTypeActual77));
            Assert.That(nationalityTypeExpected78, Is.EqualTo(nationalityTypeActual78));
            Assert.That(nationalityTypeExpected79, Is.EqualTo(nationalityTypeActual79));
            Assert.That(nationalityTypeExpected80, Is.EqualTo(nationalityTypeActual80));
            Assert.That(nationalityTypeExpected81, Is.EqualTo(nationalityTypeActual81));
            Assert.That(nationalityTypeExpected82, Is.EqualTo(nationalityTypeActual82));
            Assert.That(nationalityTypeExpected83, Is.EqualTo(nationalityTypeActual83));
            Assert.That(nationalityTypeExpected84, Is.EqualTo(nationalityTypeActual84));
            Assert.That(nationalityTypeExpected85, Is.EqualTo(nationalityTypeActual85));
            Assert.That(nationalityTypeExpected86, Is.EqualTo(nationalityTypeActual86));
            Assert.That(nationalityTypeExpected87, Is.EqualTo(nationalityTypeActual87));
            Assert.That(nationalityTypeExpected88, Is.EqualTo(nationalityTypeActual88));
            Assert.That(nationalityTypeExpected89, Is.EqualTo(nationalityTypeActual89));
            Assert.That(nationalityTypeExpected90, Is.EqualTo(nationalityTypeActual90));
            Assert.That(nationalityTypeExpected91, Is.EqualTo(nationalityTypeActual91));
            Assert.That(nationalityTypeExpected92, Is.EqualTo(nationalityTypeActual92));
            Assert.That(nationalityTypeExpected93, Is.EqualTo(nationalityTypeActual93));
            Assert.That(nationalityTypeExpected94, Is.EqualTo(nationalityTypeActual94));
            Assert.That(nationalityTypeExpected95, Is.EqualTo(nationalityTypeActual95));
            Assert.That(nationalityTypeExpected96, Is.EqualTo(nationalityTypeActual96));
            Assert.That(nationalityTypeExpected97, Is.EqualTo(nationalityTypeActual97));
            Assert.That(nationalityTypeExpected98, Is.EqualTo(nationalityTypeActual98));
            Assert.That(nationalityTypeExpected99, Is.EqualTo(nationalityTypeActual99));
            Assert.That(nationalityTypeExpected100, Is.EqualTo(nationalityTypeActual100));
            Assert.That(nationalityTypeExpected101, Is.EqualTo(nationalityTypeActual101));
            Assert.That(nationalityTypeExpected102, Is.EqualTo(nationalityTypeActual102));
            Assert.That(nationalityTypeExpected103, Is.EqualTo(nationalityTypeActual103));
            Assert.That(nationalityTypeExpected104, Is.EqualTo(nationalityTypeActual104));
            Assert.That(nationalityTypeExpected105, Is.EqualTo(nationalityTypeActual105));
            Assert.That(nationalityTypeExpected106, Is.EqualTo(nationalityTypeActual106));
            Assert.That(nationalityTypeExpected107, Is.EqualTo(nationalityTypeActual107));
            Assert.That(nationalityTypeExpected108, Is.EqualTo(nationalityTypeActual108));
            Assert.That(nationalityTypeExpected109, Is.EqualTo(nationalityTypeActual109));
            Assert.That(nationalityTypeExpected110, Is.EqualTo(nationalityTypeActual110));
            Assert.That(nationalityTypeExpected111, Is.EqualTo(nationalityTypeActual111));
            Assert.That(nationalityTypeExpected112, Is.EqualTo(nationalityTypeActual112));
            Assert.That(nationalityTypeExpected113, Is.EqualTo(nationalityTypeActual113));
            Assert.That(nationalityTypeExpected114, Is.EqualTo(nationalityTypeActual114));
            Assert.That(nationalityTypeExpected115, Is.EqualTo(nationalityTypeActual115));
            Assert.That(nationalityTypeExpected116, Is.EqualTo(nationalityTypeActual116));
            Assert.That(nationalityTypeExpected117, Is.EqualTo(nationalityTypeActual117));
            Assert.That(nationalityTypeExpected118, Is.EqualTo(nationalityTypeActual118));
            Assert.That(nationalityTypeExpected119, Is.EqualTo(nationalityTypeActual119));
            Assert.That(nationalityTypeExpected120, Is.EqualTo(nationalityTypeActual120));
            Assert.That(nationalityTypeExpected121, Is.EqualTo(nationalityTypeActual121));
            Assert.That(nationalityTypeExpected122, Is.EqualTo(nationalityTypeActual122));
            Assert.That(nationalityTypeExpected123, Is.EqualTo(nationalityTypeActual123));
            Assert.That(nationalityTypeExpected124, Is.EqualTo(nationalityTypeActual124));
            Assert.That(nationalityTypeExpected125, Is.EqualTo(nationalityTypeActual125));
            Assert.That(nationalityTypeExpected126, Is.EqualTo(nationalityTypeActual126));
            Assert.That(nationalityTypeExpected127, Is.EqualTo(nationalityTypeActual127));
            Assert.That(nationalityTypeExpected128, Is.EqualTo(nationalityTypeActual128));
            Assert.That(nationalityTypeExpected129, Is.EqualTo(nationalityTypeActual129));
            Assert.That(nationalityTypeExpected130, Is.EqualTo(nationalityTypeActual130));
            Assert.That(nationalityTypeExpected131, Is.EqualTo(nationalityTypeActual131));
            Assert.That(nationalityTypeExpected132, Is.EqualTo(nationalityTypeActual132));
            Assert.That(nationalityTypeExpected133, Is.EqualTo(nationalityTypeActual133));
            Assert.That(nationalityTypeExpected134, Is.EqualTo(nationalityTypeActual134));
            Assert.That(nationalityTypeExpected135, Is.EqualTo(nationalityTypeActual135));
            Assert.That(nationalityTypeExpected136, Is.EqualTo(nationalityTypeActual136));
            Assert.That(nationalityTypeExpected137, Is.EqualTo(nationalityTypeActual137));
            Assert.That(nationalityTypeExpected138, Is.EqualTo(nationalityTypeActual138));
            Assert.That(nationalityTypeExpected139, Is.EqualTo(nationalityTypeActual139));
            Assert.That(nationalityTypeExpected140, Is.EqualTo(nationalityTypeActual140));
            Assert.That(nationalityTypeExpected141, Is.EqualTo(nationalityTypeActual141));
            Assert.That(nationalityTypeExpected142, Is.EqualTo(nationalityTypeActual142));
        });
    }

    
}