name: SonarQube Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]

  schedule:
    - cron: "0 0 * * 6"

  workflow_dispatch:

jobs:
  call-template:
    uses: EvolutionFunding/evo.core/.github/workflows/template_sonarqube_scan_v1.yml@master
    with:
      SONARQUBE_PROJECT_KEY: 'EvolutionFunding_evo.funders.blackhorse_AYuo72DsVVnKh2iFwyr1' # Obtained from SonarQube after setting up the project from GitHub
    secrets: inherit
